import { auth } from "./firebase.js";
import { initializeAuth, getUserProfile, logout, updateUserProfile } from "./services-auth.js";
import { listUserActivities, summarizeActivities } from "./services-activity.js";

const $ = (id) => document.getElementById(id);
const ui = {
  name: $("profileName"), email: $("profileEmail"), role: $("profileRole"), bio: $("profileBio"), university: $("profileUniversity"), specialty: $("profileSpecialty"), photo: $("profilePhotoURL"), avatar: $("profileAvatar"), heading: $("profileHeading"), form: $("profileForm"), message: $("profileMessage"), save: $("profileSave"), lectures: $("statLectures"), resources: $("statResources"), videos: $("statVideos"), activities: $("statActivities"), progress: $("progressPercent"), progressBar: $("progressBar"), progressText: $("progressText"), logout: $("profileLogout")
};
function message(text="",type="info"){if(!ui.message)return;ui.message.textContent=text;ui.message.className=`profile-message ${type}`;}
function avatar(url,name){if(!ui.avatar)return;ui.avatar.innerHTML="";if(url){const img=document.createElement("img");img.src=url;img.alt=`${name||"User"} profile photo`;img.onerror=()=>avatar("",name);ui.avatar.appendChild(img);return;}ui.avatar.textContent=(name||"U").trim().charAt(0).toUpperCase()||"U";}
async function loadStats(uid){try{const activities=await listUserActivities(uid),s=summarizeActivities(activities);ui.lectures.textContent=s.lectures;ui.resources.textContent=s.resources;ui.videos.textContent=s.videos;ui.activities.textContent=s.total;const percent=Math.min(100,s.total?Math.round((new Set(activities.map(a=>a.resourceId).filter(Boolean)).size/20)*100):0);ui.progress.textContent=`${percent}%`;ui.progressBar.style.width=`${percent}%`;ui.progressText.textContent=percent?`${percent}% learning progress based on unique resources opened.`:"Start opening lectures and resources to build your progress.";}catch(e){console.warn("Stats unavailable",e);}}
async function load(){await initializeAuth();const user=auth.currentUser;if(!user){window.location.replace("../index.html");return;}const profile=await getUserProfile(user);if(!profile){window.location.replace("../index.html");return;}if(profile.role==="admin"){window.location.replace("admin.html");return;}const name=profile.fullName||user.displayName||"User",photo=profile.photoURL||user.photoURL||"";ui.name.value=name;ui.email.value=profile.email||user.email||"";ui.role.textContent="Student / User";ui.bio.value=profile.bio||"";ui.university.value=profile.university||"";ui.specialty.value=profile.specialty||"";ui.photo.value=photo;ui.heading.textContent=name;avatar(photo,name);await loadStats(user.uid);}
ui.photo?.addEventListener("input",()=>avatar(ui.photo.value.trim(),ui.name.value.trim()));
ui.form?.addEventListener("submit",async e=>{e.preventDefault();const user=auth.currentUser;if(!user)return;ui.save.disabled=true;ui.save.textContent="Saving...";message("Saving your profile...","info");try{const current=await getUserProfile(user);if(!current||current.role==="admin"){window.location.replace("admin.html");return;}await updateUserProfile(user,{fullName:ui.name.value.trim(),photoURL:ui.photo.value.trim(),bio:ui.bio.value.trim(),university:ui.university.value.trim(),specialty:ui.specialty.value.trim()});avatar(ui.photo.value.trim(),ui.name.value.trim());ui.heading.textContent=ui.name.value.trim()||"User";message("Profile updated successfully.","success");}catch(e){console.error(e);message("Could not update your profile.","error");}finally{ui.save.disabled=false;ui.save.textContent="Save Profile";}});
ui.logout?.addEventListener("click",async()=>{try{await logout();}finally{window.location.replace("../index.html");}});
load().catch(e=>{console.error("Profile startup error",e);window.location.replace("../index.html");});
