import {
  initializeAuth,
  observeAuth,
  signIn,
  signInWithGoogle,
  register,
  logout,
  ensureUserProfile,
  sendPasswordReset,
  resendVerificationEmail,
  refreshCurrentUser,
  linkPendingGoogleCredential,
  hasPendingGoogleCredential,
} from "./services-auth.js";
import { auth } from "./firebase.js";
import { listCategories } from "./services-categories.js";
import { listResources } from "./services-resources.js";
import { listVideos } from "./services-videos.js";
import { listCertificates } from "./services-certificates.js";
import { recordActivity } from "./services-activity.js";
import { startSiteAnalytics, trackContentOpen } from "./services-analytics.js";

const $ = (id) => document.getElementById(id);
const el = {
  menu: document.querySelector(".menu-toggle"), nav: document.querySelector(".nav-links"), authModal: $("authModal"), authClose: $("authClose"), authForm: $("authForm"), authEmail: $("authEmail"), authPassword: $("authPassword"), authFullName: $("authFullName"), authConfirmPassword: $("authConfirmPassword"), authMessage: $("authMessage"), authSubmit: $("authSubmit"), authTitle: $("authTitle"), authSubtitle: $("authSubtitle"), loginTab: $("authTabLogin"), registerTab: $("authTabRegister"), registerFields: $("registerFields"), authConfirmGroup: $("authConfirmGroup"), authPasswordGroup: $("authPasswordGroup"), authPasswordStrength: $("authPasswordStrength"), authForgotLink: $("authForgotLink"), authRecoveryBack: $("authRecoveryBack"), authDivider: $("authDivider"), authSecurityNote: $("authSecurityNote"), google: $("googleSignIn"), authOpen: $("authOpen"), heroSignIn: $("heroSignIn"), profileLink: $("profileLink"), dashboardLink: $("dashboardLink"), logout: $("logoutButton"), authVerification: $("authVerification"), authVerificationEmail: $("authVerificationEmail"), authResendVerification: $("authResendVerification"), authIveVerified: $("authIveVerified"), resourceGrid: $("resourceGrid"), resourceSearch: $("resourceSearch"), resourceFilter: $("resourceFilter"), resourcePagination: $("resourcePagination"), resourceEmpty: $("emptyState"), resourceLoading: $("resourceLoading"), videoGrid: $("publicVideoGrid"), videoPagination: $("videoPagination"), videoEmpty: $("videoEmpty"), certificateGrid: $("publicCertificateGrid"), certificateEmpty: $("certificateEmpty"), year: $("year")
};
const state = { profile:null, authMode:"login", busy:false, categories:[], resources:[], videos:[], certificates:[], resourcePage:1, videoPage:1 };
const PAGE_SIZE=9;

function authMessage(text="",type=""){if(!el.authMessage)return;el.authMessage.textContent=text;el.authMessage.className=`auth-message ${type}`.trim();}
function setAuthMode(mode){state.authMode=mode;const login=mode==="login",register=mode==="register",recovery=mode==="recovery";el.loginTab?.classList.toggle("active",login);el.registerTab?.classList.toggle("active",register);el.registerFields?.classList.toggle("hidden",!register);el.authConfirmGroup?.classList.toggle("hidden",!register);el.authForgotLink?.classList.toggle("hidden",!login);el.authRecoveryBack?.classList.toggle("hidden",!recovery);el.authPasswordGroup?.classList.toggle("hidden",recovery);el.authPasswordStrength?.classList.toggle("hidden",!register);el.authDivider?.classList.toggle("hidden",recovery);el.google?.classList.toggle("hidden",recovery);el.authSecurityNote?.classList.toggle("hidden",recovery);if(el.authPassword)el.authPassword.required=!recovery;if(el.authTitle)el.authTitle.textContent=login?"Welcome back":register?"Create your account":"Reset your password";if(el.authSubtitle)el.authSubtitle.textContent=login?"Sign in securely to continue your medical learning journey.":register?"Create your secure Dr.Omir learning account.":"Enter your email and we’ll send you a secure reset link.";if(el.authSubmit)el.authSubmit.textContent=login?"Sign In":register?"Create Account":"Send Reset Link";authMessage();}
function openAuth(mode="login"){setAuthMode(mode);el.authModal?.classList.add("show");el.authModal?.setAttribute("aria-hidden","false");document.body.classList.add("modal-open");setTimeout(()=>el.authEmail?.focus(),50);}
function closeAuth(){el.authModal?.classList.remove("show");el.authModal?.setAttribute("aria-hidden","true");document.body.classList.remove("modal-open");el.authForm?.reset();el.authVerification?.classList.add("hidden");el.authForm?.classList.remove("hidden");authMessage();setAuthMode("login");}
function friendlyAuthError(error){const map={"auth/invalid-credential":"The email or password is incorrect.","auth/user-not-found":"The email or password is incorrect.","auth/wrong-password":"The email or password is incorrect.","auth/invalid-email":"Enter a valid email address.","auth/email-already-in-use":"This email is already registered. Try signing in instead.","auth/weak-password":"Choose a stronger password that meets the password policy.","auth/password-does-not-meet-requirements":"Your password does not meet the current security requirements.","auth/popup-closed-by-user":"Google sign-in was cancelled.","auth/popup-blocked":"Your browser blocked the Google sign-in window. Allow pop-ups and try again.","auth/cancelled-popup-request":"Another sign-in window is already open.","auth/network-request-failed":"Network error. Check your connection and try again.","auth/too-many-requests":"Too many attempts. Please wait a little and try again.","auth/operation-not-allowed":"This sign-in method is currently unavailable.","auth/credential-already-in-use":"This Google account is already linked to another Dr.Omir account.","auth/provider-already-linked":"This sign-in method is already linked to your account.","permission-denied":"Your account could not be prepared. Please try again."};return map[error?.code]||"We couldn't complete that request. Please try again.";}
function setAuthBusy(busy,label="Please wait…"){state.busy=busy;[el.authSubmit,el.google,el.loginTab,el.registerTab].forEach(x=>{if(x)x.disabled=busy;});if(busy&&el.authSubmit)el.authSubmit.textContent=label;}
function updateNavigation(profile){state.profile=profile;const logged=Boolean(profile),admin=profile?.role==="admin";if(el.dashboardLink)el.dashboardLink.hidden=!admin;if(el.profileLink)el.profileLink.hidden=!logged||admin;if(el.authOpen)el.authOpen.hidden=logged;if(el.logout)el.logout.hidden=!logged;}
function setupNavigation(){el.menu?.addEventListener("click",()=>{const open=el.nav?.classList.toggle("active");el.menu?.setAttribute("aria-expanded",open?"true":"false")});document.querySelectorAll(".nav-links a").forEach(a=>a.addEventListener("click",()=>{el.nav?.classList.remove("active");el.menu?.setAttribute("aria-expanded","false")}));}
function showVerification(){el.authForm?.classList.add("hidden");el.authVerification?.classList.remove("hidden");if(el.authVerificationEmail)el.authVerificationEmail.textContent=auth.currentUser?.email||"your email address";const m=$("authVerificationMessage");if(m){m.textContent="Verification email sent. Check your inbox and spam folder.";m.className="auth-message success";}}
function hideVerification(){el.authVerification?.classList.add("hidden");el.authForm?.classList.remove("hidden");}
function setupAuth(){el.authOpen?.addEventListener("click",()=>openAuth());el.heroSignIn?.addEventListener("click",()=>openAuth("register"));el.authClose?.addEventListener("click",closeAuth);el.authModal?.addEventListener("click",e=>{if(e.target===el.authModal)closeAuth()});el.loginTab?.addEventListener("click",()=>{hideVerification();setAuthMode("login")});el.registerTab?.addEventListener("click",()=>{hideVerification();setAuthMode("register")});el.authForgotLink?.addEventListener("click",e=>{e.preventDefault();setAuthMode("recovery")});el.authRecoveryBack?.addEventListener("click",e=>{e.preventDefault();setAuthMode("login")});el.authForm?.addEventListener("submit",submitAuth);el.google?.addEventListener("click",googleAuth);el.authResendVerification?.addEventListener("click",resendVerification);el.authIveVerified?.addEventListener("click",checkVerification);el.logout?.addEventListener("click",async()=>{try{await logout();updateNavigation(null);}catch(e){console.error(e);}});$("authTogglePassword")?.addEventListener("click",()=>togglePassword(el.authPassword,$("authTogglePassword")));$("authToggleConfirmPassword")?.addEventListener("click",()=>togglePassword(el.authConfirmPassword,$("authToggleConfirmPassword")));$("authPassword")?.addEventListener("input",updateAuthPasswordStrength);}
function togglePassword(input,button){if(!input||!button)return;const show=input.type==="password";input.type=show?"text":"password";button.setAttribute("aria-label",show?"Hide password":"Show password");button.setAttribute("title",show?"Hide password":"Show password");button.setAttribute("aria-pressed",show?"true":"false");}
function updateAuthPasswordStrength(){
  const password=el.authPassword?.value||"";
  const panel=el.authPasswordStrength,bar=$("authPasswordStrengthBar"),text=$("authPasswordStrengthText");
  if(!panel||!bar||!text)return;
  const rules={Length:password.length>=8,Lower:/[a-z]/.test(password),Upper:/[A-Z]/.test(password),Number:/\d/.test(password),Symbol:/[^A-Za-z0-9]/.test(password)};
  Object.entries(rules).forEach(([name,met])=>$("authRule"+name)?.classList.toggle("met",met));
  const score=Object.values(rules).filter(Boolean).length;
  const level=!password||score<=2?"weak":score<=4?"medium":"strong";
  panel.dataset.level=level;
  bar.style.width=password?`${score*20}%`:"0%";
  text.textContent=password?(level==="strong"?"Strong password":level==="medium"?"Medium password":"Weak password"):"Password strength";
}

async function submitAuth(e){e.preventDefault();if(state.busy)return;const email=el.authEmail?.value.trim().toLowerCase()||"",password=el.authPassword?.value||"",fullName=el.authFullName?.value.trim()||"",confirm=el.authConfirmPassword?.value||"";if(!email){authMessage("Enter your email address.","error");return;}if(state.authMode==="recovery"){setAuthBusy(true,"Sending reset link…");authMessage("Preparing your secure reset email…","info");try{await sendPasswordReset(email);authMessage("If an account exists for this email, a password reset link has been sent. Check your inbox and spam folder.","success");}catch(error){console.error(error);authMessage(error?.code==="auth/invalid-email"?"Enter a valid email address.":"We couldn't send the reset link right now. Please try again.","error");}finally{setAuthBusy(false);setAuthMode("recovery");}return;}if(!password){authMessage("Enter your password.","error");return;}if(state.authMode==="register"&&!fullName){authMessage("Enter your full name.","error");return;}if(state.authMode==="register"&&password!==confirm){authMessage("Passwords do not match.","error");return;}if(state.authMode==="register"&&password.length<8){authMessage("Use at least 8 characters for your password.","error");return;}setAuthBusy(true,state.authMode==="login"?"Signing in…":"Creating account…");authMessage("Please wait…","info");try{if(state.authMode==="login"){const profile=await signIn(email,password);if(hasPendingGoogleCredential()){await linkPendingGoogleCredential(auth.currentUser);authMessage("Google has been linked to your account. Redirecting…","success");}if(profile?.role==="admin"){window.location.replace("Pages/admin.html");return;}if(auth.currentUser&&!auth.currentUser.emailVerified){showVerification();authMessage("Please verify your email before continuing.","info");return;}closeAuth();return;}const profile=await register(email,password,fullName);if(profile?.role==="admin"){window.location.replace("Pages/admin.html");return;}showVerification();}catch(error){console.error("Authentication error:",error);if(error?.code==="auth/account-exists-with-different-credential")authMessage("This email already has a password account. Sign in with that password now to link Google securely.","error");else authMessage(friendlyAuthError(error),"error");}finally{setAuthBusy(false);el.authSubmit.textContent=state.authMode==="login"?"Sign In":state.authMode==="register"?"Create Account":"Send Reset Link";}}
async function googleAuth(){if(state.busy)return;setAuthBusy(true,"Connecting to Google…");authMessage("Connecting securely to Google…","info");try{const profile=await signInWithGoogle();if(profile?.role==="admin"){window.location.replace("Pages/admin.html");return;}closeAuth();}catch(error){console.error("Google authentication error:",error);authMessage(friendlyAuthError(error),"error");}finally{setAuthBusy(false);el.authSubmit.textContent=state.authMode==="login"?"Sign In":state.authMode==="register"?"Create Account":"Send Reset Link";}}
async function resendVerification(){if(state.busy)return;setAuthBusy(true,"Sending…");try{await resendVerificationEmail();const m=$("authVerificationMessage");if(m){m.textContent="A fresh verification email has been sent. Check your inbox and spam folder.";m.className="auth-message success";}}catch(error){console.error(error);const m=$("authVerificationMessage");if(m){m.textContent=error?.code==="auth/too-many-requests"?"Please wait before requesting another email.":"We couldn't send another verification email yet.";m.className="auth-message error";}}finally{setAuthBusy(false);}}
async function checkVerification(){if(state.busy)return;setAuthBusy(true,"Checking…");try{const user=await refreshCurrentUser();if(user?.emailVerified){closeAuth();return;}const m=$("authVerificationMessage");if(m){m.textContent="Your email is not verified yet. Open the latest email, verify it, then try again.";m.className="auth-message error";}}catch(error){console.error(error);const m=$("authVerificationMessage");if(m){m.textContent="We couldn't check verification status. Please refresh and try again.";m.className="auth-message error";}}finally{setAuthBusy(false);}}
function categoryName(resource){if(resource.categoryName)return resource.categoryName;return state.categories.find(c=>c.id===resource.categoryId)?.name||resource.category||"Other";}
function resourceType(resource){const t=`${resource.title||""} ${resource.url||""}`.toLowerCase();if(t.includes("pdf"))return "PDF";if(t.includes("youtube")||t.includes("youtu.be"))return "VIDEO";if(t.includes("docs.google"))return "DOC";return "FILE";}
function paginate(items,page){const pages=Math.max(1,Math.ceil(items.length/PAGE_SIZE));const safe=Math.min(page,pages);return {items:items.slice((safe-1)*PAGE_SIZE,safe*PAGE_SIZE),pages,page:safe};}
function renderPager(target,pages,current,onPage){if(!target)return;target.innerHTML="";if(pages<=1)return;const add=(label,disabled,page,active=false)=>{const b=document.createElement("button");b.type="button";b.textContent=label;b.disabled=disabled;b.className=active?"active":"";b.onclick=()=>onPage(page);target.appendChild(b);};add("←",current===1,current-1);for(let p=1;p<=pages;p++){if(p===1||p===pages||Math.abs(p-current)<=2)add(String(p),false,p,p===current);else if(!target.lastChild?.classList.contains("ellipsis")){const s=document.createElement("span");s.className="ellipsis";s.textContent="…";target.appendChild(s);}}add("→",current===pages,current+1);}
function renderResources(){if(!el.resourceGrid)return;const term=(el.resourceSearch?.value||"").trim().toLowerCase(),cat=el.resourceFilter?.value||"all";const filtered=state.resources.filter(r=>{const text=`${r.title||""} ${r.description||""} ${categoryName(r)}`.toLowerCase();const catMatch=cat==="all"||r.categoryId===cat||(String(r.category||"").toLowerCase()===categoryName(state.categories.find(c=>c.id===cat)||{}).toLowerCase());return text.includes(term)&&catMatch;});const pg=paginate(filtered,state.resourcePage);state.resourcePage=pg.page;el.resourceGrid.innerHTML="";pg.items.forEach(r=>{const card=document.createElement("article");card.className="resource-card reveal visible";const icon=document.createElement("div");icon.className="resource-icon";icon.textContent=resourceType(r);const body=document.createElement("div");body.className="resource-body";const meta=document.createElement("div");meta.className="resource-meta";meta.textContent=`${categoryName(r).toUpperCase()} · ${resourceType(r)}`;const title=document.createElement("h3");title.textContent=r.title||"Untitled resource";const desc=document.createElement("p");desc.textContent=r.description||"Educational resource.";const actions=document.createElement("div");actions.className="resource-actions";const open=document.createElement("a");open.className="btn btn-primary small";open.href=r.url||"#";open.target="_blank";open.rel="noopener noreferrer";open.textContent="Open File";open.onclick=()=>{ trackContentOpen({type:"resource",contentId:r.id,title:r.title||""}).catch(console.warn); if(state.profile?.uid) recordActivity({uid:state.profile.uid,type:categoryName(r).toLowerCase()==="lecture"?"lecture_opened":"resource_opened",resourceId:r.id,title:r.title||""}).catch(console.warn); };const ext=document.createElement("a");ext.className="text-link";ext.href=r.url||"#";ext.target="_blank";ext.rel="noopener noreferrer";ext.textContent="Open ↗";actions.append(open,ext);body.append(meta,title,desc,actions);card.append(icon,body);el.resourceGrid.appendChild(card);});el.resourceEmpty.style.display=filtered.length?"none":"block";renderPager(el.resourcePagination,pg.pages,state.resourcePage,p=>{state.resourcePage=p;renderResources();});}
function populateCategoryFilter(){el.resourceFilter.innerHTML='<option value="all">All categories</option>';state.categories.forEach(c=>{const o=document.createElement("option");o.value=c.id;o.textContent=c.name;el.resourceFilter.appendChild(o);});}
function renderVideos(){if(!el.videoGrid)return;const pg=paginate(state.videos,state.videoPage);state.videoPage=pg.page;el.videoGrid.innerHTML="";pg.items.forEach(v=>{const card=document.createElement("article");card.className="video-card reveal visible";const cover=document.createElement("a");cover.className="video-cover";cover.href=v.url||"#";cover.target="_blank";cover.rel="noopener noreferrer";cover.innerHTML="<span>▶</span>";cover.onclick=()=>{ trackContentOpen({type:"video",contentId:v.id,title:v.title||""}).catch(console.warn); if(state.profile?.uid) recordActivity({uid:state.profile.uid,type:"video_watched",resourceId:v.id,title:v.title||""}).catch(console.warn); };const content=document.createElement("div");content.className="video-content";const meta=document.createElement("div");meta.className="resource-meta";meta.textContent=`VIDEO · ${categoryName(v).toUpperCase()}`;const h=document.createElement("h3");h.textContent=v.title||"Medical video";const p=document.createElement("p");p.textContent=v.description||"Educational video.";const a=document.createElement("a");a.className="text-link";a.href=v.url||"#";a.target="_blank";a.rel="noopener noreferrer";a.textContent="Watch video ↗";content.append(meta,h,p,a);card.append(cover,content);el.videoGrid.appendChild(card);});el.videoEmpty.style.display=state.videos.length?"none":"block";renderPager(el.videoPagination,pg.pages,state.videoPage,p=>{state.videoPage=p;renderVideos();});}
function renderCertificates(){if(!el.certificateGrid)return;el.certificateGrid.innerHTML="";state.certificates.forEach(c=>{const card=document.createElement("article");card.className="certificate-card reveal visible";const image=document.createElement("div");image.className="certificate-image";if(c.imageUrl){const img=document.createElement("img");img.src=c.imageUrl;img.alt=c.title||"Certificate";img.loading="lazy";image.appendChild(img);}else image.textContent="🏆";const h=document.createElement("h3");h.textContent=c.title||"Certificate";const p=document.createElement("p");p.textContent=[c.date,c.description].filter(Boolean).join(" · ");card.append(image,h,p);if(c.url){const a=document.createElement("a");a.className="text-link certificate-link";a.href=c.url;a.target="_blank";a.rel="noopener noreferrer";a.textContent="View certificate ↗";card.appendChild(a);}el.certificateGrid.appendChild(card);});el.certificateEmpty.style.display=state.certificates.length?"none":"block";}
async function loadContent(){el.resourceLoading.hidden=false;try{[state.categories,state.resources,state.videos,state.certificates]=await Promise.all([listCategories(),listResources(),listVideos(),listCertificates()]);populateCategoryFilter();renderResources();renderVideos();renderCertificates();}catch(e){console.error("Content loading error",e);el.resourceEmpty.style.display="block";el.resourceEmpty.textContent="Content is temporarily unavailable.";}finally{el.resourceLoading.hidden=true;}}
async function handleAuth(user){if(!user){updateNavigation(null);return;}try{const profile=await ensureUserProfile(user);updateNavigation(profile);}catch(e){console.error(e);updateNavigation(null);}}
function setupReveal(){const obs=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add("visible");obs.unobserve(x.target);}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(x=>obs.observe(x));}
async function start(){setupNavigation();setupAuth();setupReveal();startSiteAnalytics("home").catch(console.warn);if(el.year)el.year.textContent=new Date().getFullYear();el.resourceSearch?.addEventListener("input",()=>{state.resourcePage=1;renderResources();});el.resourceFilter?.addEventListener("change",()=>{state.resourcePage=1;renderResources();});await initializeAuth();observeAuth(handleAuth);await loadContent();}
start().catch(console.error);
